name: Build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  # Stage 1: Quick validation checks (30-60 seconds)
  quick-checks:
    name: Quick Validation
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install linting tools
        run: |
          pip install flake8 mypy black isort

      - name: Check code formatting (Black)
        run: |
          black --check src/ tests/ || (echo "❌ Code formatting issues found. Run 'black src/ tests/' to fix." && exit 1)

      - name: Check import sorting (isort)
        run: |
          isort --profile black --check-only src/ tests/ || (echo "❌ Import sorting issues found. Run 'isort --profile black src/ tests/' to fix." && exit 1)

      - name: Lint code (Flake8)
        run: |
          flake8 src/ tests/ --max-line-length=100 --extend-ignore=E203,W503

      - name: Type checking (Mypy)
        run: |
          mypy src --ignore-missing-imports

  # Stage 2: Tests and SonarCloud analysis (2-3 minutes)
  sonarcloud:
    name: Tests & SonarCloud Analysis
    needs: quick-checks  # Only run if quick checks pass
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full history for SonarQube

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run tests with coverage
        run: |
         PYTHONPATH=. python -m pytest tests/ --cov=src --cov-report=xml --cov-report=term

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: SonarCloud Quality Gate Check
        uses: SonarSource/sonarqube-quality-gate-action@v1.2.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        timeout-minutes: 5
